version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    allow:
      - all
    assignees:
      - Frank-Mayer
    reviewers:
      - Frank-Mayer
    target-branch: dev
    versioning-strategy: increase
