name: Deploy to Pages

on:
  push:
    branches: ["main"]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  win:
    runs-on: windows-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ">=1.21.6"
          cache: true
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          go build -ldflags="-s -w" -o yab-windows-amd64.exe ./cmd/yab
          go build -ldflags="-s -w -H=windowsgui" -o install-yab-windows-amd64.exe ./cmd/installer
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: "./yab-windows-amd64.exe"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: "./install-yab-windows-amd64.exe"

  mac:
    runs-on: macos-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ">=1.21.6"
          cache: true
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: go test ./... -v
      - name: Build
        run: |
          go build -ldflags="-s -w" -o yab-darwin-amd64 ./cmd/yab/
          go build -ldflags="-s -w" -o install-yab-darwin-amd64 ./cmd/installer/
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: "./yab-darwin-amd64"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: "./install-yab-darwin-amd64"
      - name: Build ARM
        run: |
          env GOARCH=arm64 go build -ldflags="-s -w" -o yab-darwin-arm64 ./cmd/yab/
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: "./yab-darwin-arm64"

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ">=1.21.6"
          cache: true
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build -ldflags="-s -w" -o yab-linux-amd64 ./cmd/yab
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: "./yab-linux-amd64"
      - name: Build ARM
        run: env GOARCH=arm64 go build -ldflags="-s -w" -o yab-linux-arm64 ./cmd/yab
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: "./yab-linux-arm64"

  deploy:
    needs:
      - win
      - mac
      - ubuntu
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: LS
        run: ls -l artifact
      - name: Generate index.html
        run: |
          cd artifact
          echo '<!DOCTYPE html>' >> index.html
          echo '<html lang="en-US"><head>' >> index.html
          echo '<title>Yab Artifacts</title>' >> index.html
          echo '<style>:root{color-scheme: light dark; font-family: sans-serif;}</style>' >> index.html
          echo '</head><body>' >> index.html
          echo '<h1>Artifacts</h1>' >> index.html
          echo '<ul>' >> index.html
          echo '<li><a download="yab" href="yab-darwin-amd64">yab-darwin-amd64</a></li>' >> index.html
          echo '<li><a download="yab" href="yab-darwin-arm64">yab-darwin-arm64</a></li>' >> index.html
          echo '<li><a download="yab" href="yab-linux-amd64">yab-linux-amd64</a></li>' >> index.html
          echo '<li><a download="yab" href="yab-linux-arm64">yab-linux-arm64</a></li>' >> index.html
          echo '<li><a download="yab.exe" href="yab-windows-amd64.exe">yab-windows-amd64.exe</a></li>' >> index.html
          echo '</ul>' >> index.html
          echo '<h2>Installer</h2>' >> index.html
          echo '<ul>' >> index.html
          echo '<li><a download="install-yab" href="install-yab-darwin-amd64">install-yab-darwin-amd64</a></li>' >> index.html
          echo '<li><a download="install-yab.exe" href="install-yab-windows-amd64.exe">install-yab-windows-amd64.exe</a></li>' >> index.html
          echo '</ul>' >> index.html
          echo '</body></html>' >> index.html
          cd ..
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./artifact"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
