name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  test-mac:
    runs-on: macos-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ">=1.21.6"
          cache: true
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./... -v
  test-win:
    runs-on: windows-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ">=1.21.6"
          cache: true
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: go test ./... -v
